first_tutorial.txt: targets no longer end in BUILD
Removes targets of the form: path/dir/BUILD:target which cause errors:

ValueError: Spec tests/java/com/pants/examples/hello/greet/BUILD:greet
has BUILD as the last path part and BUILD is reserved files